export default {
  CREATE_POST: 'CREATE_POST',
  REMOVE_POST: 'REMOVE_POST',
  GET_POSTS: 'GET_POSTS',
  GET_ALL_POSTS: 'GET_ALL_POSTS',
  LIKE_POST: 'LIKE_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
};
